# -*- coding: utf-8 -*-
"""EXERCISE1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ObYeq6d_4N30IeRtun7QtC0KY50y1pni
"""

print("hello,world!")

if 5> 2:
  print("five is greater than 2")

if 5> 2:
  print("5 is greater than two!")
if 5> 2:
  print("5 is greater than two!")

thislist = ["apple","banana","cherry"]
print(thislist)

thislist = ["apple","banana","cherry","apple","cherry"]
print(thislist)

thislist = ["apple","banana","cherry"]
print(thislist[1])

thislist = ["apple","banana","cherry","orange","kiwi","melon","mango"]
print(thislist[2:5])

thistuple=("apple","banana", "cherry")
print(thistuple)

thisset={"apple","banana","cherry"}
print(thisset)

class myclass:
  x=5
p1 = myclass()
print(p1.x)

class person:
  def __init__(self,name,age):
    self.name = name
    self.age = age

p1=person("john",36)

print(p1.name)
print(p1.age)

class point:
  def __init__(self,x=0,y=0):
    self.x=x
    self.y=y

  def add_points(self,other):
    x = self.x + other.x
    y= self.y + other.x
    return point(x,y)

p1=point(1,2)
p2=point(2,3)

p3=p1.add_points(p2)

print((p3.x,p3.y))

class person:
  def __init__(self,name,age):
    self.name=name
    self.age=age

  def __lt__(self,other):
    return self.age < other.age

p1=person("alice",20)
p2=person("bob",30)

print(p1<p2)
print(p2<p1)

x=divmod(5,2)
print(x)

